### ISSUE TITLE
Heterogeneous zips

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/infinite-list#15]
See https://github.com/haskell/core-libraries-committee/issues/229#issuecomment-1890596069.

```haskell
zipWithInfinite :: Data.Traversable.Traversable t => (a -> b -> c) -> Infinite a -> t b -> t c
zipWithInfinite f = (snd .) . Data.Traversable.mapAccumL (\(x :< xs) b -> (xs, f x b))

zipInfinite :: Data.Traversable.Traversable t => Infinite a -> t b -> t (a, b)
zipInfinite = zipWithInfinite (,)
```

Do we need a variant with `mapAccumR`?..

**Comment by Bodigrim** [comment]
OTOH, given that the library is meant to be imported qualified, it's kinda stupid to say `Inf.zipInfinite`. I think `Inf.align` and `Inf.alignWith` would be better names. 

This might still be confusing, because `Data.Align.align` says "Functors supporting an [align](https://hackage.haskell.org/package/semialign-1.3/docs/Data-Align.html#v:align) operation that takes the union of non-uniform shapes", while we are explicitly taking the (trivial) intersection of shapes.

Also remains unclear whether we need a variant with `mapAccumR` and how to name it.

**Comment by ChickenProp** [comment]
I might suggest having `Traversable` in the name? `Infinite.zipTraversable` and `Infinite.zipWithTraversable`?

> Also remains unclear whether we need a variant with `mapAccumR` and how to name it.

Personally I don't see a need for this, but if there was one I'd probably just append `R` to other names. It's not symmetrical but that seems okay?

**Comment by Bodigrim** [comment]
`zipWithTraversable` sounds a bit misleading as if "with" refers to `Traversable`. 

Maybe just `heteroZip` and `heteroZipWith`? Or is it too math-ish?

**Comment by ChickenProp** [comment]
Oh, yeah. `zipTraversableWith`?

I like `heteroZip[With]`, but I'm a math person.

**Comment by Bodigrim** [comment]
If both of use like `heteroZip[With]`, let's just go with it?..

**Comment by ChickenProp** [comment]
Sounds good to me.

**Comment by Bodigrim** [comment]
I agree that we do not need a right version upfront. 

@ChickenProp would you like to prepare a PR?
