### ISSUE TITLE
Monad instance

### ISSUE THREAD

**Issue by BlackCapCoder** [Bodigrim/infinite-list#2]
https://github.com/Bodigrim/infinite-list/blob/4925a36302816da3a31ebbdfe14c5e818e93549a/src/Data/List/Infinite.hs#L322-L332

The monad instance picks the main diagonal `(0,0), (1,1), (2,2) ..`. What is the motivation for this over a more traditional striping instance, IE:
```haskell
-- a0 :<
-- a1 :< b0 :<
-- a2 :< b1 :< c0 :<
-- ...
join =
  unfoldr \case
    (x:<xs):<xss ->
      (x, zipWith (:<) xs xss)
```

**Comment by BlackCapCoder** [comment]
Unlike the current implementation, the striping one is reversible:

```haskell
-- cantor's π function
π z = (x, y)
  where
    w = div (isqrt (8*z+1)-1) 2
    t = div (w*w + w) 2
    y = z - t
    x = w - y

unπ (x,y) =
  div ((x+y)*(x+y+1)) 2 + y

----

ix s (π→(i,j)) =
  s !! j !! i

nats = go 0 where
  go n = n :< go (n+1)

join' ∷ Infinite (Infinite a) → Infinite a
join' s =
  map (ix s) nats

duplicate ∷ Infinite a → Infinite (Infinite a)
duplicate s =
  map (!! s) $
    nats & map \i ->
    nats & map \j ->
      unπ (j, i)
```

**Comment by Bodigrim** [comment]
Does your implementation satisfy monad laws?

**Comment by BlackCapCoder** [comment]
Yes it does. It is the same instance as `control-monad-omega` or `Moore` from machines

**Comment by BlackCapCoder** [comment]
However, `liftM2` is nondeterminism I believe rather than zipping, so the  `Applicative` and `Monad` instances would not be consistent with each other.

Does the current implementation give `liftM2 = zipWith`?

**Comment by BlackCapCoder** [comment]
With the current instance and `MonadComprehensions`, `[ (a,b) | a <- foo, b <- bar ]` and [ (a,b) | a <- foo | b <- bar ]` does the exact same thing, but with the new instance it would do what you'd expect.

**Comment by Bodigrim** [comment]
> Yes it does. It is the same instance as `control-monad-omega` or `Moore` from machines

Documentation of `control-monad-omega` is clear that it does **not** satisfy monad laws.

**Comment by BlackCapCoder** [comment]
> Documentation of control-monad-omega is clear that it does not satisfy monad laws.

I might be wrong here, but I think this is only because it is implemented for finite lists. I'll investigate!

**Comment by BlackCapCoder** [comment]
Negative. An obvious counter-example is `m = m >>= pure`. It might be a lawful bind instance, though, but we don't provide Bind!
