### ISSUE TITLE
Add uncycle

### ISSUE THREAD

**Issue by BlackCapCoder** [Bodigrim/infinite-list#3]
A common application for this function is to pretty print an infinite list as `<prefix> ++ cycle <cycle>`, common lisp does this. More applications can be found on [wikipedia](https://en.wikipedia.org/wiki/Cycle_detection#Applications) and the [rational-list](https://hackage.haskell.org/package/rational-list-1.0.0.0/docs/Data-RationalList.html#g:6) package. rational-list is implemented in terms of `Data.Sequence`.

Here's an untested implementation. I'll open a PR if this is something you want :heart:
```haskell
-- ~O(3n).
--   uncycle (pre `prependList` cycle cy) = (pre, cy)
--   uncycle (iterate (+1) 0) = fix id
--
uncycle ∷ Eq a ⇒ Infinite a → ([a], NonEmpty a)
uncycle s = rollup s ρ
  where
    -- ~O(2n). Brent's algorithm
    go n π λ t (h:<hs)
      | t == h = (λ, n, h:<hs)
      | π == λ = go (n+1) (π+π) 1 h hs
      | let    = go n π (λ+1) t hs

    -- O(length pre).
    rollup (t:<ts) (h:<hs)
      | t == h               = ([], NE.fromList (take cy (t:<ts)))
      | (l,r) ← rollup ts hs = (t:l, r)

    -- O(cy-off).
    ρ = drop (cy-off) s2

    -- 'cy' is the length of the cycle
    (cy, n, s2)
      | x:<xs ← s = go 0 1 1 x xs

    -- number of iterations used by go
    steps = 2^n + cy - 1

    -- the index of the final hare in go
    off = mod steps cy
```

**Comment by BlackCapCoder** [comment]
Since we have an infinite lazy list and only `Eq`, we can never be sure that we have found "the biggest cycle". We could return the rest of the infinite list so you can keep uncons'ing cycles until you are sufficiently convinced, though..

**Comment by BlackCapCoder** [comment]
This might be better. Rollup rolls a window of length `cy` through the stream in a bankers queue.

```haskell
uncycle ∷ Eq a ⇒ Infinite a → ([a], NonEmpty a, Infinite a)
uncycle s@(x:<xs) = go 1 1 x xs
  where
    go π λ t (h:<hs)
      | t == h = rollup nil nil `uncurry` splitAt λ s
      | π == λ = go (π+π) 1 h hs
      | let    = go π (λ+1) t hs

    rollup f q (t:ts) (h:<hs)
      | t == h      = (list f, t NE.:| (ts ++ list q), h:<hs)
      | let         = rollup (snoc f t) (snoc q h) ts hs
    rollup f q _ hs = rollup f nil (list q) hs

    snoc f a z = f (a:z)
    list f     = f []
    nil      z = z
```

**Comment by Bodigrim** [comment]
Is it possible to write 
```haskell
uncycle ∷ Eq a ⇒ Infinite a → Infinite ([a], NonEmpty a)
```
such that if `uncycle xs = (pref0, cycle0) :< (pref1, cycle1) :< (pref2, cycle2)` then all of `pref0 <> cycle0 <> cycle0`, `pref0 <> pref1 <> cycle1 <> cycle1`, `pref0 <> pref1 <> pref2 <> cycle2 <> cycle2` are prefixes of `xs`?

The point is to generate successive approximations to the "true" generator.

**Comment by BlackCapCoder** [comment]
That's a good call. That would just be `uncycle' (uncycle->(a,b,c)) = (a,b) :< uncycle' c`

**Comment by BlackCapCoder** [comment]
Something like this perhaps?

```haskell
-- | O(3n) time, O(1) space.
-- | Group elements into disjoint sets
groupDisjoint :: Eq a => Infinite a -> Infinite (NonEmpty a)
groupDisjoint = map (\(pre,cyc) -> pre <> cyc) . groupDisjointEx

-- | Hinge algorithm for `groupDisjoint`
-- | Given any endomorphic function `f`, the exist two unique list `p` and `c` such that
-- | `iterate f = p ++ cycle c`. The result of this function is `(p,c) :< repeat ([], c)`
groupDisjointEx :: Eq a => Infinite a -> Infinite ([a], NonEmpty a) 
```

**Comment by BlackCapCoder** [comment]
Sorry, I think I misread your question. Let's draw out an example!
```haskell
xs = [0,1,2,1,2] `prependList` cycle [3,4]

-- old uncycle
uncycle xs = ([0], [1,2]) :< ([1,2], [3,4]) :< ([], [3,4]) :< ..


uncycle' xs = ([0], [1,2]) :< (pref1, [3,4,3,4]) :< (pref2, [3,4,3,4,3,4]) :< ...

pref0 <> pref1 <> cycle1 <> cycle1 `prefixOf` xs
[0] <> pref1 <> [3,4,3,4] <> [3,4,3,4] `prefixOf` xs
pref1 = [1,2,1,2]

uncycle' xs = ([0], [1,2]) :< ([1,2,1,2], [3,4,3,4]) :< (pref2, [3,4,3,4,3,4]) :< ...

```
I am confused. That design seems very weird to me

**Comment by Bodigrim** [comment]
BTW have you seen https://hackage.haskell.org/package/quadratic-irrational-0.1.1/docs/Numeric-QuadraticIrrational.html#g:4 ?

**Comment by BlackCapCoder** [comment]
Oh no- down the rabbit hole! Nice library!

**Comment by Bodigrim** [comment]
Thinking more about it, my suggestion in https://github.com/Bodigrim/infinite-list/issues/3#issuecomment-1321244042 is probably misleading. 

Essentially we want to generate a sequence of (prefix, cycle) "converging" to an actual infinite list. It's not true that prefixes of such "approximations" are monotonic. E. g., consider [1,2,3,3,2,3,3]: the first approximation would be prefix [1,2] and cycle [3], but the next approximation is prefix [1] and cycle [2,3,3]. 

Here is a better property: for each consequent (prefix1, cycle1) and (prefix2, cycle2) in `uncycle xs` the common prefix of `xs` and `prefix2 ++ cycle cycle2` is longer than the common prefix of `xs` and `prefix1 ++ cycle cycle1`. Does it make sense?

**Comment by Bodigrim** [comment]
Closing as stalled, feel free to reopen if there are resources to execute.
