### ISSUE TITLE
>>= not lawful because of indexing

### ISSUE THREAD

**Issue by olafklinke** [Bodigrim/infinite-list#7]
The implementation of `>>=`  uses indexing over a finite type and therefore can not be lawful due to overflows. Consider the following value and Kleisli map.
```
nats :: Infinite Integer
nats = 0 :< fmap (1+) nats

k :: Integer -> Infinite Bool
k i = go i where
    go 0 = repeat False
    go n = True :< go (n-1)
```
The expected behaviour is that `nats >>= k == pure False` since the n-th element of `k n` is `False` by definition and `>>=`  is supposed to select the n-th element from the image of element at the n-th position. However, one can observe that actually `nats >>= k` is eventually `True` after `genericDrop`ping sufficiently many elements from the result. (To observe this in finite time, change the index type in `!!` to a smaller `Word` but that does not change the line of argumentation.)

It should be possible to implement `>>=`  without indexing, because it is possible to implement `join` without indexing:
```
join :: Infinite (Infinite a) -> Infinite a
join ((x :< _) :< xss) = x :< join (fmap tail xss)
```
Needless to say, this issue also causes `<*>` to be unequal to `ap`.

**Suggested fix:** Either implement `>>=` in terms of `join` above or some some equivalent index-free method, or change the type of `!!` to use an unbounded index type such as `Natural`.

**Comment by Bodigrim** [comment]
The easiest would be to replace `xs !! n` with `head . (genericDrop n xs)`, taking care that `n :: Natural` index is eagerly evaluated.

But I'm not sure I'm convinced:

> To observe this in finite time, change the index type in `!!` to a smaller `Word` but that does not change the line of argumentation.

If we agree to accept such argument, one could claim that `(!!)` is not lawful for the same reasons. The type of `(!!)` is a deliberate choice, see https://github.com/Bodigrim/infinite-list#indexing.

**Comment by olafklinke** [comment]
Are there laws for `(!!)` ? The documentation only says that `(!!n)` returns the n-th element, and that is true regardless of the word size. It is not claimed that `(!!)` is able to index the entire infinite list and I think everyone should be fine with that being so, in particular since you identified performance penalties for `Natural`. 
To clarify: I do not suggest using a smaller word size in production. Only for the sake of counterexample I changed the word size, e.g.
```
type Index = Word8
(!!) :: Infinite a -> Index -> a
(!!) = -- function body unchanged
```
However, I do not see the point in having a `Monad` instance if it is only lawful up to index 2^n for some number n. `Foldable` is also omitted for good reasons, so maybe the same can be said about `Monad`.

**Comment by Bodigrim** [comment]
OK. I'll accept a PR replacing `xs !! n` with `head . (genericDrop n xs)`. Bonus points for adding fusion rules for `genericDrop`.

**Comment by olafklinke** [comment]
I know too little about getting the firing order of rewrite rules right. Maybe you can help there? My PR compiles with warnings that the rule I added may never fire. I believe it would be of advantage if `genericDrop (n+1)` which is called by the recursion in the `go` function inside `>>=` is simplified to `genericDrop n . tail`.
